name: sabaki-go # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.52.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Go playing game
description: |
  Go playing game

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  sabaki_icon.png
title: Sabaki

apps:
  sabaki:
    command: sabaki-v0.52.2-linux-x64.AppImage
parts:
  sabaki:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      sabaki: build/
      sabaki.1: man/man1/

architectures:
  - build-on: amd64

